name: golden_balance_flutter
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^3.0.1
  freezed_annotation:
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  cached_network_image: ^3.0.0
  dio: ^4.0.0
  flutter_secure_storage: ^4.1.0
  flutter_phoenix: ^1.0.0
  google_sign_in: ^5.0.3
  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.3
  firebase_auth: ^1.1.3
  firebase_storage: ^8.1.0
  flutter_image_compress: ^1.0.0
  fluttertoast: ^8.0.7
  path_provider: ^2.0.2
  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  freezed:
  build_runner:


flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansCJKkr
      fonts:
        - asset: fonts/NotoSansCJKkr/NotoSansCJKkr-Bold.ttf
          weight: 700
        - asset: fonts/NotoSansCJKkr/NotoSansCJKkr-Medium.ttf
          weight: 500
        - asset: fonts/NotoSansCJKkr/NotoSansCJKkr-Regular.ttf
          weight: 400
        - asset: fonts/NotoSansCJKkr/NotoSansCJKkr-Light.ttf
          weight: 200

    - family: Skia
      fonts:
        - asset: fonts/Skia/Skia.ttf
          weight: 400
    - family: PermanentMarker
      fonts:
        - asset: fonts/PermanentMarker/PermanentMarker-Regular.ttf
          weight: 400

  assets:
    - images/
    - icons/